### ISSUE TITLE
Dynamic elements in :olp

### ISSUE THREAD

**Issue by Alexander-Miller** [progfolio/doct#14]
I split the items I plan and log in my org files based on the year, so the outline paths for my capture templates often look like `("Tasks" "2020" "Habits")`. In order to not have to update the templates for every new year I have been trying to dynamically built the olps by including a calls to functions like `(format-time-string "%Y")`. 

That doesn't work in doct because it expects the `:olp` to be a list of strings, so I had to fall back to always providing a full `:function`.

It'd be great if doct allowed dynamic elements in its `:olp`, maybe by having `(eval (exp))` elements next to strings, or applying the `"%(exp)"` replacement as in the template.

Note that I am not asking for the dynamic parts to be re-evaluated every time capture is triggered, doing it just once in the `doct` call is perfectly sufficient for my use-case.

**Comment by progfolio** [comment]
You can use the backquote syntax to have the year dynamically computed when doct converts the declaration to the template:

```emacs-lisp
(let ((org-capture-templates
       (doct `("OLP for this year" :keys "y"
               :file "/tmp/2020-olp.org"
               :olp ("Tasks" ,(format-time-string "%Y") "Habits")))))
  (org-capture nil "y"))
```
The year will only be computed during conversion, so if it changes during usage (say you keep Emacs running on New Year's Eve into Jan 1st) you'll have re-evaluate/set your `org-capture-templates` again for it to change. Not much of a hassle, but something to be aware of.

The other caveat with using an olp this way is that the path must exist in the file first. If any element of it does not, org-capture will throw an error similar to:

```emacs-lisp
(error "Heading not found on level X: ...")
```
Again, not too much of a hassle. Once the path exists, you're set for a year. You could also automate this by specifying a `:function` that ensures the path exists.

```emacs-lisp
(let ((org-capture-templates
       (doct `("OLP for this year" :keys "y"
               :file "/tmp/2020-olp.org"
               :function my/get-create-olp ;; finds or creates the olp in the target file
               :olp ("Tasks" ,(format-time-string "%Y") "Habits")))))
  (org-capture nil "y"))
```
Within `my/get-create-olp` , `(doct-get :olp)` could be used to access the otherwise ignored outline path.
Does that help?

**Comment by Alexander-Miller** [comment]
> You can use the backquote syntax to have the year dynamically computed 

I was pretty sure I had tried that. Guess I was doing it wrong :man_facepalming:.
Thanks for the help!
