### ISSUE TITLE
Method to combine doct with org-roam templates? 

### ISSUE THREAD

**Issue by shrysr** [progfolio/doct#18]
I am a happy user of doct, and a recent user of org-roam. I'm unable to figure out the method of using the org-roam function with the doct capture templates. I would appreciate advice on this. 

So I have multiple templates defined in functions like 
```lisp 
(defun sr/fun/todo-act-date ()
'("* %{todo-state} %?"
":PROPERTIES:"
":CREATED: %<%Y-%m-%d %a %H:%M>"
":PLANNED: %^t"
":END:"))
```

And then org-capture templates are defined something like:

```lisp
(setq org-capture-templates
      (doct '(
              ("Todo" :keys "t"
               :file "~/my_org/roam/00_private/todo-global.org"
               :prepend t
               :children (("inbox"
                           :keys "t"
                           :type entry
                           :headline "@inbox"
                           :todo-state "TODO"
                           :template sr/fun/todo-act-date)))
```
I have tried using the template keyword to use the org-roam-capture function, but this resulted in a syntax error.

Org-roam's manual (https://org-roam.readthedocs.io/en/master/templating/) mentions that it leverages org-capture under the hood. 

Please let me know if you require any further information.

**Comment by progfolio** [comment]
See #16 
If that doesn't do the trick, let me know.

**Comment by progfolio** [comment]
I've reworked the code in #16 to be a little more flexible:

https://gist.github.com/progfolio/2871f12099be3913a1c61a3c3062f4fd

This package provides `doct-org-roam`  which can be used just like `doct` with the addition of an `:org-roam` keyword for org-roam specific keywords.

Example usage with the default org-roam template:

```emacs-lisp
;;after requiring the package in the gist above...
(setq org-roam-capture-templates
      (doct-org-roam '("default"
                       :keys "d"
                       :type plain
                       :function org-roam--capture-get-point
                       :template "%?"
                       :org-roam ( :file-name "%<%Y%m%d%H%M%S>-${slug}"
                                   :head "#+title: ${title}\n")
                       :unnarrowed t)))
```
I don't think I'll publish this on MELPA or anywhere else due to its limited scope, but it should take care of basic integration between doct and org-roam. I'm going to close this issue, but feel free to comment if you need more help.

As for your example, the `:template` keyword accepts a variable as its value. `sr/fun/todo-act-date` is returning the same list every time it is called, so you may want to store it in a variable. e.g.

```emacs-lisp
(defvar sr/todo-act-date '("* %{todo-state} %?"
                           ":PROPERTIES:"
                           ":CREATED: %<%Y-%m-%d %a %H:%M>"
                           ":PLANNED: %^t"
                           ":END:"))
```
