### ISSUE TITLE
How to reference the template description string?

### ISSUE THREAD

**Issue by philipsd6** [progfolio/doct#27]
I find myself creating a lot of templates similar to these:

```elisp
(let ((org-capture-templates
       (doct '("Call" :keys "c"
               :type entry
               :file "/tmp/test.org"
               :template "* %{desc} %{comm-type}: %?"
               :children
                (("Tech Support" :keys "t" :desc "Tech Support" :comm-type "Call")
                 ("Billing"      :keys "b" :desc "Billing"      :comm-type "Call")
                 ("Admin"        :keys "a" :desc "Admin"        :comm-type "Call")
                 )))))
  (org-capture nil "ct"))

```

The redundancy of having the `:desc` and `:comm-type` properties being the same as the template title/descriptions bothers me, but I haven't been able to figure out how to refer to the description of my template, let alone the description of the parent group. Is something like this possible? At least the child ones if not the parent?

**Comment by philipsd6** [comment]
OK, I dumped `org-capture-plist` and answered the most important part of my question. This works for the children level:

```elisp
(let ((org-capture-templates
       (doct '("Call" :keys "c"
               :type entry
               :file "/tmp/test.org"
               :template "* %{doct-name} %{comm-type}: %?"
               :children
                (("Tech Support" :keys "t" :comm-type "Call")
                 ("Billing"      :keys "b" :comm-type "Call")
                 ("Admin"        :keys "a" :comm-type "Call")
                 )))))
  (org-capture nil "ct"))
```
That gets me to 90% happy. I was just expecting to get that from `:description` as that's what that is called in the org-capture template documentation.

If there's some way to access the parent group `:doct-name` feel free to update, otherwise we can close this.

**Comment by progfolio** [comment]
> I was just expecting to get that from :description as that's what that is called in the org-capture template documentation.

I store the name as `:doct-name` in order to avoid key name conflicts with user metadata.

> If there's some way to access the parent group :doct-name feel free to update

What you have in your example is not a group.
Groups are special cases of parent declarations which store metadata but are not added to the resultant list of templates.
See:

<https://github.com/progfolio/doct#group>

At one point I stored the entire declaration list with each template.
This was a recursive data structure when `:children`  where involved and allowed accessing the parent declaration.
I'll have to look over my notes for the reason why I decided against keeping all that info.
It may have been a complexity issue, bugs that arose, or just a decision to keep things simpler.
I don't recall at the moment, but I'll take a look and reconsider the idea.

In any case, you can simplify your current declarations by storing the `:comm-type` property on the parent declaration.
It will act as the default `:comm-type` for each child declaration unless you explicitly override it:

```emacs-lisp
(progn
  (require 'org-capture)
  (let ((org-capture-templates
          (doct '("Call" :keys "c"
                  :file "/tmp/test.org"
                  :template "* %{doct-name} %{comm-type}: %?"
                  :comm-type "Call"
                  :children (("Tech Support" :keys "t")
                             ("Billing"      :keys "b")
                             ("Admin"        :keys "a"))))))
    (org-capture nil "ct")))
```

Does that help?

**Comment by philipsd6** [comment]
For my current example it absolutely does!
