### ISSUE TITLE
Doct with org-journal

### ISSUE THREAD

**Issue by DarkBuffalo** [progfolio/doct#34]
Hi,
First of all thank you for the good work done on DOCT.

## Context
I tried to adapt the capture provided by [org-journal ](https://github.com/bastibe/org-journal/blob/master/README.org#journal-capture-template)with DOCT but it does not work.
``` emacs-lisp
(defun org-journal-find-location ()
  ;; Open today's journal, but specify a non-nil prefix argument in order to
  ;; inhibit inserting the heading; org-capture will insert the heading.
  (org-journal-new-entry t)
  (unless (eq org-journal-file-type 'daily)
    (org-narrow-to-subtree))
  (goto-char (point-max)))

(setq org-capture-templates '(("j" "Journal entry" plain (function org-journal-find-location)
                               "** %(format-time-string org-journal-time-format)%^{Title}\n%i%?"
                               :jump-to-captured t :immediate-finish t)))
```
## Errors
- When I leave the 2 ** in the template it shows me an error
```
Warning (doct): expanded :template "** %(format-time-string org-journal-time-format)%^{Title}
%i%?" in the "Journal" declaration is not a valid Org entry.
  Are you missing the leading ’*’?
```
- When I leave a single * it does not indent the hourly headline
``` 
* mercredi, 13/07/2022
:PROPERTIES:
:CREATED:  20220713
:END:
* 10:11 essai
test
```
## Template
``` emacs-lisp						
("Journal" :keys "j"
	:icon ("book" :set "octicon" :color "orange")
	:function ,(defun org-journal-find-location ()
				;; Open today's journal, but specify a non-nil prefix argument in order to
				;; inhibit inserting the heading; org-capture will insert the heading.
				(org-journal-new-entry t)
				(unless (eq org-journal-file-type 'yearly)
					(org-narrow-to-subtree))
				(goto-char (point-max)))
	:template ("** %(format-time-string org-journal-time-format)%^{Title}"
			"%i%?"))
```

Does the problem come from my adaptation or is this a bug ?

**Comment by DarkBuffalo** [comment]
maybe that would also interest @bastibe

**Comment by progfolio** [comment]
> Hi,
First of all thank you for the good work done on DOCT.

Glad you're finding it useful. Thank you for the thorough bug report.

It looks like you have two separate issues here.
Let's deal with them one at a time.

>      When I leave the 2 ** in the template it shows me an error

When I wrote the validator, I likely copy pasted a check from just above where entries are checked for leading stars. Instead of `string-prefix-p`, the check needs to use `string-match-p` because we want to check via a regexp. I've fixed this on the "development" branch as demonstrated by these two tests:

[Yodel](https://github.com/progfolio/yodel) Report (2022-07-13 12:45:51):

```emacs-lisp
(yodel
  :user-dir "doct-master"
  :packages*
  doct
  :post*
  (doct
   '("test"
     :keys "t"
     :file ""
     :template "**")))
```

<details><summary>STDOUT:</summary>

```emacs-lisp
Loading /tmp/doct-master/straight-bootstrap-snippet.el (source)...
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done
Cloning doct...
Cloning doct...done
Building doct...
Building doct...done

Warning (doct): expanded :template "**" in the "test" declaration is not a valid Org entry.
  Are you missing the leading ’*’?
```

</details>
<details><summary>Environment</summary>

- **emacs version**: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
 of 2022-06-28
- **system type**: gnu/linux

<details open><summary>Packages</summary>

| Name                                      | Branch | Commit                                                                            | Date       | Source |
|-------------------------------------------|--------|-----------------------------------------------------------------------------------|------------|--------|
| [doct](https://github.com/progfolio/doct) | master | https://github.com/progfolio/doct/commit/8464809754f3316d5a2fdcf3c01ce1e8736b323b | 2022-05-29 | melpa  |

</details>

</details>

[Yodel](https://github.com/progfolio/yodel) Report (2022-07-13 12:45:53):

```emacs-lisp
(yodel
  :user-dir "doct-development"
  :packages*
  '(doct
    :branch "development")
  :post*
  (doct
   '("test"
     :keys "t"
     :file ""
     :template "**")))
```

<details><summary>STDOUT:</summary>

```emacs-lisp
Loading /tmp/doct-development/straight-bootstrap-snippet.el (source)...
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done
Cloning doct...
Cloning doct...done
Building doct...
Building doct...done
```

</details>
<details><summary>Environment</summary>

- **emacs version**: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
 of 2022-06-28
- **system type**: gnu/linux

<details open><summary>Packages</summary>

| Name                                      | Branch      | Commit                                                                            | Date       | Source |
|-------------------------------------------|-------------|-----------------------------------------------------------------------------------|------------|--------|
| [doct](https://github.com/progfolio/doct) | development | https://github.com/progfolio/doct/commit/202f714b0076373ddd307ef1b2910d94099bbd5e | 2022-07-13 | melpa  |

</details>

</details>

I'll merge that into the master branch in a few minutes and you can try it on either branch.

As for your second issue:

>  When I leave a single * it does not indent the hourly headline

My hunch is that everything is working as expected.
The example utilizes a `:function` which is responsible for placing point.
Then the template is inserted as is.
So with a first-level heading template, I'd expect a first level heading.

Org capture will adjust the level of the heading in the template if you specify certain targets,
such as `file+heading`, but not  when a general point-placing function is used.

Does that help?

**Comment by progfolio** [comment]
I'm assuming this fixed the issue. If not, feel free to comment and we can reopen this issue.
